import type { InventoryData, Product, Supplier, Lot, Movement, MovementType } from '../../src/features/inventory/types';
export const today = '2026-09-10';
export const supplier: Supplier = { id: '00000000-0000-4000-8000-000000000010', name: 'Dental de prueba', contact: 'Contacto de prueba', phone: '5550000000', email: 'fixture@example.test', notes: 'Datos sintéticos', active: true, version: 1 };
const lot = (id: string, number: string | null, available: string, expiryDate: string | null, expiryStatus = 'NORMAL', expiryLabel: string | null = null): Lot => ({ id, number, available, expiryDate, expiryStatus, expiryLabel, receivedAt: today, initialQuantity: available, unitCost: '12.50', supplier });
const product = (id: string, name: string, unit: string, stock: string, minimumStock: string, lots: Lot[] = []): Product => ({ id, name, unit, stock, minimumStock, lots, category: 'Consumibles', description: null, supplierId: supplier.id, supplier, referenceCost: '125.50', active: true, version: 1, usableStock: stock, expiredStock: '0', stockStatus: Number(stock) === 0 ? 'EMPTY' : Number(stock) < Number(minimumStock) ? 'LOW' : 'NORMAL', nextExpiry: null, expiring: false, expired: false });
export function fixtures(): InventoryData {
  const gloves = product('gloves', 'Guantes nitrilo M', 'caja', '2', '5', [lot('lot-gloves', null, '2', null)]);
  const articaine = product('articaine', 'Articaína', 'cartucho', '20', '10', [lot('lot-articaine', 'AR-001', '20', null)]); articaine.category = 'Anestesia';
  const resin = product('resin', 'Resina A2', 'jeringa', '11', '2', [lot('lot-near', 'RX-001', '3', '2026-09-28', 'EXPIRING', 'Caduca en 18 días'), lot('lot-future', 'RX-002', '8', '2027-03-20', 'NORMAL', 'Caduca en 191 días')]); resin.category = 'Restauración'; resin.expiring = true; resin.nextExpiry = '2026-09-28';
  const expired = product('expired', 'Ácido grabador', 'jeringa', '2', '1', [lot('lot-expired', 'AC-001', '2', '2026-09-05', 'EXPIRED', 'Caducado hace 5 días')]); expired.expired = true; expired.usableStock = '0'; expired.expiredStock = '2'; expired.stockStatus = 'EMPTY';
  const inactive = product('inactive', 'Material desactivado', 'ml', '0', '0'); inactive.active = false;
  return { today, timeZone: 'America/Mexico_City', canManage: true, expiryWarningDays: 30, suppliers: [structuredClone(supplier)], products: [gloves, articaine, resin, product('masks', 'Cubrebocas', 'caja', '0', '1'), expired, inactive], movements: [], summary: { active: 5, low: 1, empty: 2, expiring: 1, expired: 1 } };
}
export function movement(product: Product, type: MovementType, quantity: string, lotId: string): Movement { return { id: `move-${Math.random()}`, productId: product.id, lotId, type, quantity, effectiveDate: today, reason: 'Registro de prueba', note: null, createdAt: '2026-09-10T16:42:00Z', createdBy: { user: { firstName: 'Doctora', lastName: 'Prueba' } }, lot: { number: product.lots.find(l => l.id === lotId)?.number || null, product: { name: product.name, unit: product.unit } } }; }
