version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: yes-farma-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: yes_farma_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yes-farma-backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/yes_farma_db?schema=public
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./backend/src:/usr/src/app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yes-farma-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
