services:
  db:
    image: postgres:15-alpine
    container_name: yes-farma-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: yes_farma_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - proxy-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yes-farma-backend
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/yes_farma_db?schema=public
      - PORT=3000
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./backend/src:/usr/src/app/src
    networks:
      - proxy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yes-farma-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - proxy-network

volumes:
  pgdata:

networks:
  proxy-network:
    external: true
