import type { Budget } from './types';
import { budgetLabels, formatMoney } from './types';
export interface BudgetDocument { clinic: { name: string; timeZone: string; dentalClinicalTools?: boolean }; patient: { firstName: string; lastName: string; secondLastName: string | null }; budget: Budget }
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function budgetPrintHtml({ clinic, patient, budget: b }: BudgetDocument) {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Presupuesto ${escape(b.folio || b.id.slice(0,8))}</title><style>
  *{box-sizing:border-box}body{font:14px Arial,sans-serif;color:#172033;margin:0;padding:24px;overflow-wrap:anywhere}main{max-width:900px;margin:auto}h1{font-size:26px}header{border-bottom:2px solid #1d4ed8;padding-bottom:16px}table{border-collapse:collapse;width:100%;table-layout:fixed;margin:24px 0}th,td{text-align:left;padding:10px 6px;border-bottom:1px solid #ddd;vertical-align:top}th:last-child,td:last-child{width:25%;text-align:right}small{display:block;white-space:pre-wrap;margin-top:6px}tr{break-inside:avoid}thead{display:table-header-group}.totals{text-align:right;break-inside:avoid}footer{margin-top:32px;color:#555}button{padding:12px 18px;margin-bottom:16px;min-height:44px;border:1px solid #1d4ed8;border-radius:8px;background:#2563eb;color:white;cursor:pointer}button:hover{background:#1d4ed8}button:active{background:#1e40af}button:focus-visible{outline:3px solid #2563eb;outline-offset:3px}@page{margin:15mm}@media print{body{padding:0}button,.instructions{display:none}main{max-width:none}}@media(max-width:500px){body{padding:12px}th,td{padding:8px 3px}}
  </style></head><body><main><button onclick="window.print()">Imprimir / guardar como PDF</button><p class="instructions">Para descargar el documento, selecciona «Guardar como PDF» en el diálogo de impresión.</p><header><h1>${escape(clinic.name)}</h1><h2>Presupuesto · ${escape((b.folio || b.id.slice(0,8).toUpperCase()))}</h2></header><p>Paciente: ${escape([patient.firstName,patient.lastName,patient.secondLastName].filter(Boolean).join(' '))}</p><p>Fecha: ${escape(new Date(b.createdAt).toLocaleDateString('es-MX',{timeZone:clinic.timeZone}))} · Estado: ${escape(budgetLabels[b.status])}</p><table><thead><tr><th>Procedimiento / descripción</th><th>Importe (MXN)</th></tr></thead><tbody>${b.items.map(i => `<tr><td>${escape(i.name)}${clinic.dentalClinicalTools !== false && i.toothNumber ? `<small>Pieza FDI ${i.toothNumber}</small>` : ''}${i.description ? `<small>${escape(i.description)}</small>` : ''}</td><td>${escape(formatMoney(i.price))}</td></tr>`).join('')}</tbody></table><section class="totals"><p>Subtotal: ${escape(formatMoney(b.subtotal))}</p><p>Descuento: ${escape(formatMoney(b.discount))}</p><h2>Total: ${escape(formatMoney(b.total))}</h2><p>Pagado: ${escape(formatMoney(b.paid!))}</p><p><strong>Saldo pendiente: ${escape(formatMoney(b.balance!))}</strong></p></section><footer>Importes en MXN. Presupuesto para control interno de la clínica.</footer></main></body></html>`;
}
