import { useState, type FormEvent, type ReactNode } from 'react';
import { Modal } from '../../shared/components/Modal/Modal';
import { inventoryApi } from './api';
import type { Product, Supplier, MovementType } from './types';
import { actions, buttonClass, secondaryButtonClass, fieldClass, categories, dateLabel } from './presentation';

function FormModal({ title, children, submit, onClose, action }: { title: string; children: ReactNode; submit: (data: FormData) => Promise<void>; onClose: () => void; action: string }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await submit(data); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar'); } finally { setBusy(false); } }
  return <Modal onClose={() => { if (!busy) onClose(); }} closeOnBackdrop={!busy} closeOnEscape={!busy}><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-5 sm:p-6 shadow-xl space-y-4"><h2 className="text-xl font-bold">{title}</h2>{error && <p role="alert" className="p-3 rounded-lg bg-red-50 text-red-700">{error}</p>}<fieldset disabled={busy} className="space-y-4 min-w-0">{children}</fieldset><div className="flex flex-wrap justify-end gap-2 border-t border-slate-200 pt-4"><button type="button" disabled={busy} className={secondaryButtonClass} onClick={onClose}>Cancelar</button><button disabled={busy} className={buttonClass}>{busy ? 'Registrando…' : action}</button></div></form></Modal>;
}
const value = (data: FormData, key: string) => String(data.get(key) || '').trim();
const nullable = (data: FormData, key: string) => value(data, key) || null;
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-medium space-y-1"><span>{label}</span>{children}</label>; }
function SupplierSelect({ suppliers, selected }: { suppliers: Supplier[]; selected?: string | null }) { return <Field label="Proveedor"><select className={fieldClass} name="supplierId" defaultValue={selected || ''}><option value="">Sin proveedor</option>{suppliers.filter(s => s.active || s.id === selected).map(s => <option key={s.id} value={s.id}>{s.name}{!s.active ? ' (inactivo)' : ''}</option>)}</select></Field>; }
export function ProductForm({ product, suppliers, onClose, onSaved }: { product?: Product; suppliers: Supplier[]; onClose: () => void; onSaved: (message: string) => void }) {
  return <FormModal title={product ? 'Editar producto' : 'Nuevo producto'} action={product ? 'Guardar producto' : 'Crear producto'} onClose={onClose} submit={async data => {
    await inventoryApi.product({ name: value(data, 'name'), description: nullable(data, 'description'), category: value(data, 'category'), unit: value(data, 'unit'), minimumStock: value(data, 'minimumStock'), supplierId: nullable(data, 'supplierId'), referenceCost: nullable(data, 'referenceCost'), active: data.get('active') === 'on', ...(product ? { expectedVersion: product.version } : {}) }, product?.id); onSaved('Producto guardado.');
  }}>
    <Field label="Nombre"><input autoFocus required maxLength={200} name="name" defaultValue={product?.name} className={fieldClass} /></Field>
    <div className="grid grid-cols-2 gap-3"><Field label="Categoría"><input required maxLength={100} name="category" list="inventory-categories" defaultValue={product?.category || 'Consumibles'} className={fieldClass} /><datalist id="inventory-categories">{categories.map(c => <option key={c}>{c}</option>)}</datalist></Field><Field label="Unidad de medida"><input required maxLength={50} name="unit" placeholder="caja, cartucho, ml…" defaultValue={product?.unit} className={fieldClass} /></Field></div>
    <Field label="Stock mínimo"><input required name="minimumStock" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" defaultValue={product?.minimumStock || '0'} className={fieldClass} /></Field>
    <SupplierSelect suppliers={suppliers} selected={product?.supplierId} />
    <details><summary className="cursor-pointer text-blue-700 font-semibold py-2">Descripción y costo de referencia (opcional)</summary><div className="space-y-3 pt-2"><Field label="Descripción"><textarea name="description" maxLength={2000} defaultValue={product?.description || ''} className={fieldClass} /></Field><Field label="Costo de referencia por unidad (MXN)"><input name="referenceCost" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" defaultValue={product?.referenceCost || ''} className={fieldClass} /></Field></div></details>
    <label className="flex items-center gap-2 min-h-11"><input type="checkbox" name="active" defaultChecked={product?.active ?? true} />Producto activo</label>{product && <p className="text-sm text-slate-500">Desactivar conserva lotes e historial. La unidad no puede cambiar después del primer movimiento.</p>}
  </FormModal>;
}
export function SupplierForm({ supplier, onClose, onSaved }: { supplier?: Supplier; onClose: () => void; onSaved: (message: string) => void }) {
  return <FormModal title={supplier ? 'Editar proveedor' : 'Nuevo proveedor'} action="Guardar proveedor" onClose={onClose} submit={async data => {
    await inventoryApi.supplier({ name: value(data, 'name'), contact: nullable(data, 'contact'), phone: nullable(data, 'phone'), email: nullable(data, 'email'), notes: nullable(data, 'notes'), active: data.get('active') === 'on', ...(supplier ? { expectedVersion: supplier.version } : {}) }, supplier?.id); onSaved('Proveedor guardado.');
  }}>{(['name', 'contact', 'phone', 'email'] as const).map(key => <Field key={key} label={{ name: 'Nombre', contact: 'Contacto (opcional)', phone: 'Teléfono (opcional)', email: 'Email (opcional)' }[key]}><input className={fieldClass} name={key} required={key === 'name'} type={key === 'email' ? 'email' : key === 'phone' ? 'tel' : 'text'} maxLength={key === 'phone' ? 50 : key === 'email' ? 254 : 200} defaultValue={supplier?.[key] || ''} /></Field>)}<Field label="Notas (opcional)"><textarea name="notes" maxLength={2000} defaultValue={supplier?.notes || ''} className={fieldClass} /></Field><label className="flex items-center gap-2 min-h-11"><input name="active" type="checkbox" defaultChecked={supplier?.active ?? true} />Proveedor activo</label></FormModal>;
}
export function MovementForm({ product, type, suppliers, today, onClose, onSaved }: { product: Product; type: MovementType; suppliers: Supplier[]; today: string; onClose: () => void; onSaved: (message: string) => void }) {
  const adds = type === 'ENTRY' || type === 'ADJUSTMENT_IN';
  const lots = product.lots.filter(l => type === 'ADJUSTMENT_IN' || Number(l.available) > 0);
  const [lotId, setLotId] = useState(adds ? '' : lots.find(l => type !== 'CONSUMPTION' || l.expiryStatus !== 'EXPIRED')?.id || '');
  const selected = lots.find(l => l.id === lotId);
  const newLot = adds && !lotId;
  return <FormModal title={actions[type]} action={actions[type]} onClose={onClose} submit={async data => {
    const result = await inventoryApi.move(product.id, { type, quantity: value(data, 'quantity'), lotId: lotId || null, effectiveDate: value(data, 'effectiveDate'), reason: value(data, 'reason'), note: nullable(data, 'note'), ...(newLot ? { number: nullable(data, 'number'), expiryDate: nullable(data, 'expiryDate'), supplierId: nullable(data, 'supplierId'), unitCost: nullable(data, 'unitCost') } : {}) }); onSaved(result.message);
  }}>
    <div className="p-3 rounded-xl bg-blue-50"><p className="font-semibold">{product.name}</p><p>Disponible: {product.usableStock} {product.unit}</p>{Number(product.expiredStock) > 0 && <p className="text-amber-800">{product.expiredStock} {product.unit} caducados; no utilizables.</p>}</div>
    {type !== 'ENTRY' && <Field label="Existencia / lote"><select name="lotId" required={!adds} value={lotId} onChange={e => setLotId(e.target.value)} className={fieldClass}><option value="">{adds ? 'Nueva existencia' : 'Selecciona un lote'}</option>{lots.map(l => <option key={l.id} value={l.id} disabled={type === 'CONSUMPTION' && l.expiryStatus === 'EXPIRED'}>{l.number || `Sin número · ${dateLabel(l.receivedAt)}`} · {l.available} {product.unit}{l.expiryLabel ? ` · ${l.expiryLabel}` : ''}</option>)}</select><span className="block text-xs text-slate-500">Ordenados por caducidad más cercana. Elige la existencia que usarás.</span></Field>}
    {selected && <p className="text-sm">Disponible en esta existencia: <strong>{selected.available} {product.unit}</strong>{selected.expiryLabel && <span className="block text-amber-800">{selected.expiryLabel}</span>}</p>}
    <Field label={`Cantidad (${product.unit})`}><input name="quantity" autoFocus required type="number" min="0.001" step="0.001" max={!adds ? selected?.available || '0' : '99999999999.999'} inputMode="decimal" className={fieldClass} /></Field>
    <Field label="Fecha del movimiento"><input type="date" name="effectiveDate" required defaultValue={today} min={selected?.receivedAt.slice(0, 10)} max={today} className={fieldClass} /></Field>
    {newLot && <><SupplierSelect suppliers={suppliers} selected={product.supplier?.active ? product.supplierId : null} /><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Field label="Número de lote (opcional)"><input name="number" maxLength={100} className={fieldClass} /></Field><Field label="Caducidad (opcional)"><input name="expiryDate" type="date" className={fieldClass} /></Field></div><p className="text-xs text-slate-500">Una entrada caducada se registra para trazabilidad, pero no estará disponible para consumo.</p><Field label="Costo por unidad (MXN, opcional)"><input name="unitCost" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" className={fieldClass} /></Field></>}
    {type === 'WASTE' ? <Field label="Motivo de merma"><select name="reason" required className={fieldClass}><option value="">Selecciona el motivo</option>{['Material roto', 'Contaminación', 'Caducidad', 'Daño', 'Error', 'Otro'].map(r => <option key={r}>{r}</option>)}</select></Field> : <Field label={`Motivo${type.startsWith('ADJUSTMENT') ? ' (obligatorio)' : ' (opcional)'}`}><input name="reason" required={type.startsWith('ADJUSTMENT')} maxLength={500} className={fieldClass} /></Field>}
    <Field label="Nota (opcional)"><textarea name="note" maxLength={2000} className={fieldClass} /></Field>
  </FormModal>;
}
