import type { Prescription } from './types';
import { directions } from './types';
const escape = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function prescriptionPrintHtml(r: Prescription) {
  const s = r.snapshot;
  if (!s || r.status === 'DRAFT') throw new Error('Solo las recetas emitidas tienen un documento imprimible.');
  const p = s.professional;
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Receta ${escape(s.folio)}</title><style>
  *{box-sizing:border-box}body{font:12pt Arial,sans-serif;color:#172033;margin:0;padding:24px;overflow-wrap:anywhere}main{max-width:186mm;margin:auto}header{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #334155;padding-bottom:12px}h1{font-size:18pt;margin:0 0 10px}h2{font-size:14pt;margin:0 0 8px}h3{font-size:12pt;margin:0 0 6px}p{margin:6px 0;white-space:pre-wrap}section{padding:12px 0;border-bottom:1px solid #cbd5e1}.medication{break-inside:avoid}.signature{margin:36px auto 0;text-align:center;break-inside:avoid;max-width:100mm}.signature hr{border:0;border-top:1px solid #172033}small{font-size:10pt}.folio{font:10pt monospace}.void-watermark{display:none}.cancelled{color:#991b1b;border:3px solid #991b1b;padding:12px;font-weight:bold;font-size:18pt;margin:12px 0}button{padding:12px;cursor:pointer}.controls{margin-bottom:24px}footer{margin-top:20px;font-size:9pt} @page{size:letter;margin:15mm 15mm 20mm} @media print{body{padding:0}.controls{display:none}main{max-width:none}.cancelled{color:#000}.void-watermark{display:block;position:fixed;top:45%;left:0;width:100%;text-align:center;transform:rotate(-28deg);font-size:42pt;font-weight:bold;opacity:.16;z-index:10;pointer-events:none}footer{font-size:8pt}} </style></head><body><main>
  <div class="controls"><button onclick="window.print()">Imprimir / guardar como PDF</button><p>Selecciona papel Carta. Para descargar, elige «Guardar como PDF». Desactiva encabezados y pies del navegador.</p></div>
  <header><div><h1>${escape(s.clinic.name)}</h1><p>${escape(p.address)}</p>${p.phone ? `<p>Tel. ${escape(p.phone)}</p>` : ''}</div><div><h2>RECETA ODONTOLÓGICA</h2><small>Folio interno YESKIRA</small><p class="folio">${escape(s.folio)}</p><p>Fecha: ${escape(new Date(s.issuedAt).toLocaleDateString('es-MX', { timeZone: s.clinic.timeZone }))}</p></div></header>
  ${r.status === 'CANCELLED' ? `<div class="void-watermark">RECETA ANULADA</div><div class="cancelled">RECETA ANULADA</div><p>Motivo: ${escape(r.cancellationReason)}</p><p>Anulada: ${escape(new Date(r.cancelledAt!).toLocaleDateString('es-MX', { timeZone: s.clinic.timeZone }))}</p>` : ''}
  <section><h3>PACIENTE</h3><p>${escape(s.patient.name)}</p><p>Fecha de nacimiento: ${escape(s.patient.birthDate.split('-').reverse().join('/'))}</p></section>
  <section><h3>PROFESIONAL</h3><p>${escape(p.name)}</p>${p.specialty ? `<p>${escape(p.specialty)}</p>` : ''}<p>Cédula profesional: ${escape(p.license)}${p.specialtyLicense ? ` · Cédula de especialidad: ${escape(p.specialtyLicense)}` : ''}</p></section>
  ${s.items.map(i => `<section class="medication"><h2>Rp.</h2><h3>${escape(i.medication.toUpperCase())} ${escape(i.concentration)}${i.brand ? ` (${escape(i.brand)})` : ''}</h3><p>${escape(i.form)}</p><p><strong>Modo de uso:</strong> ${escape(directions(i))}</p><p>Cantidad: ${escape(i.quantity)}</p>${i.instructions ? `<p>${escape(i.instructions)}</p>` : ''}</section>`).join('')}
  ${s.generalInstructions ? `<section><h3>INDICACIONES GENERALES</h3><p>${escape(s.generalInstructions)}</p></section>` : ''}
  <div class="signature"><hr><p>Firma del profesional</p><p>${escape(p.name)}</p><p>Cédula profesional: ${escape(p.license)}</p></div><footer>${escape(s.folio)} · ${r.status === 'CANCELLED' ? 'RECETA ANULADA' : 'Receta clínica ordinaria · Para firma física'}</footer></main></body></html>`;
}
